version: '3.1'
 
services:     
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: meesign
      POSTGRES_PASSWORD: mysecretpassword # WARNING: hardcoded secret, don't use in prod
      POSTGRES_DB: meesign
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
 
volumes:
  db-data: